/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 * @Description Generates NOC PDF with polished subsidiary names, Rich Text remarks, and automated footer.
 */
define(['N/render', 'N/record', 'N/format', 'N/log'], (render, record, format, log) => {

    const onRequest = (context) => {
        try {
            // 1. GET THE RECORD ID FROM THE URL
            const recId = context.request.parameters.recId;
            const recType = 'customrecord_noc'; 

            if (!recId) {
                context.response.write('Error: Missing Record ID in URL.');
                return;
            }

            // 2. LOAD DATA FROM THE NOC RECORD
            const objRec = record.load({ type: recType, id: recId });

            const refNo = objRec.getValue({ fieldId: 'name' }) || '';
            const rawDate = objRec.getValue({ fieldId: 'custrecord_noc_docdate' });
            const passportNo = objRec.getValue({ fieldId: 'custrecord_passport_number' }) || '';
            const remarks = objRec.getValue({ fieldId: 'custrecord_noc_remarks' }) || ''; // Rich Text Field
            const employeeId = objRec.getValue({ fieldId: 'custrecord_employee' });
            
            // CLEAN SUBSIDIARY NAME: Remove hierarchy (Parent : Child) and keep only the last part
            let subsidiaryFullText = objRec.getText({ fieldId: 'custrecord_noc_subsidiary' }) || '';
            let cleanSubsidiary = subsidiaryFullText;
            if (cleanSubsidiary.indexOf(':') > -1) {
                let parts = cleanSubsidiary.split(':');
                cleanSubsidiary = parts[parts.length - 1].trim();
            }

            if (!employeeId) {
                context.response.write('Error: Employee not selected on NOC record.');
                return;
            }

            // 3. LOAD THE EMPLOYEE RECORD FOR DYNAMIC MAPPING
            const empRec = record.load({ type: 'employee', id: employeeId });
            
            const empLegalName = empRec.getValue({ fieldId: 'custentity_hris_emplegalname' }) || empRec.getValue({ fieldId: 'entityid' });
            const nationality = empRec.getText({ fieldId: 'custentity_hris_empnationality' }) || '';
            const designation = empRec.getText({ fieldId: 'title' }) || empRec.getText({ fieldId: 'custentity_hris_empdesignation' }) || '';
            const gender = empRec.getText({ fieldId: 'custentity_hris_empgender' });
            const dojRaw = empRec.getValue({ fieldId: 'hiredate' }) || empRec.getValue({ fieldId: 'custentity_hris_date_of_joining' });

            // Format Dates
            const formattedDate = formatNocDate(rawDate);
            const formattedDoj = dojRaw ? format.format({ value: dojRaw, type: format.Type.DATE }) : '';
            
            // Gender-based Prefix
            const titlePrefix = (gender === 'Male' || gender === '1') ? 'Mr.' : 'Ms.';

            // 4. BUILD THE XML CONTENT
            let xml = '<?xml version="1.0" encoding="UTF-8"?>';
            xml += '<!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd">';
            xml += '<pdf>';
            xml += '<head>';
            xml += '  <style type="text/css">';
            xml += '    @page { size: A4; margin: 1in; }'; 
            xml += '    body { font-family: serif; font-size: 11pt; color: black; }';
            xml += '    table { width: 100%; border-collapse: collapse; table-layout: fixed; }';
            // Signature styling
            xml += '    .subsidiary-bold { font-size: 11pt; font-weight: bold; margin-top: 5pt; }';
            // Remarks styling
            xml += '    .remarks-container { font-size: 11pt; line-height: 150%; margin-top: 15pt; width: 100%; }';
            xml += '  </style>';
            
            // FOOTER MACRO
            xml += '  <macrolist>';
            xml += '    <macro id="myfooter">';
            xml += '      <table width="100%">';
            xml += '        <tr>';
            xml += '          <td align="left" style="font-size: 8pt; color: #333333;">Page <pagenumber/> of <totalpages/></td>';
            xml += '          <td align="right" style="font-size: 8pt; font-style: italic; color: #666666;">This is an automated document generated by the system</td>';
            xml += '        </tr>';
            xml += '      </table>';
            xml += '    </macro>';
            xml += '  </macrolist>';
            xml += '</head>';
            
            xml += '<body footer="myfooter" footer-height="20mm">';

            // --- SECTION 1: HEADER ---
            xml += '<table width="100%">';
            xml += '  <tr>';
            xml += '    <td align="left" width="50%"><b>Ref: ' + escapeXml(refNo) + '</b></td>';
            xml += '    <td align="right" width="50%">' + formattedDate + '</td>';
            xml += '  </tr>';
            xml += '</table>';

            // Spacing
            xml += '<table width="100%"><tr height="100px"><td></td></tr></table>';

            // --- SECTION 2: HEADING ---
            xml += '<table width="100%">';
            xml += '  <tr>';
            xml += '    <td align="center" style="font-size: 13pt;"><b><u>NO OBJECTION LETTER</u></b></td>';
            xml += '  </tr>';
            xml += '</table>';

            // Spacing
            xml += '<table width="100%"><tr height="60px"><td></td></tr></table>';

            // --- SECTION 3: BODY CONTENT ---
            xml += '<table width="100%">';
            xml += '  <tr>';
            xml += '    <td align="left" style="line-height: 160%;">';
            xml += '      This is to certify that <b>' + titlePrefix + ' ' + escapeXml(empLegalName) + '</b>, is an ';
            xml += '      <b>' + escapeXml(nationality) + ' National</b>, holding a ';
            xml += '      Passport No. <b>' + escapeXml(passportNo) + '</b> is working with the company in the capacity of ';
            xml += '      <b>' + escapeXml(designation) + '</b>, from <b>' + formattedDoj + '</b>.';
            
            // Remarks mapping (Rich Text - Tags allowed)
            if (remarks) {
                xml += '      <div class="remarks-container">' + remarks + '</div>';
            }
            xml += '    </td>';
            xml += '  </tr>';
            xml += '</table>';

            // Spacing before signature
            xml += '<table width="100%"><tr height="100px"><td></td></tr></table>';

            // --- SECTION 4: SIGNATURE AREA ---
            xml += '<table width="100%">';
            xml += '  <tr><td style="font-size: 11pt;"><b>For</b></td></tr>';
            // Cleaned Subsidiary Name (Bold and No Hierarchy)
            xml += '  <tr><td class="subsidiary-bold"><b>AL Najma Al Fareeda International Group.</b></td></tr>';
            xml += '  <tr height="80px"><td></td></tr>';
            xml += '  <tr><td>....................................................</td></tr>';
            xml += '  <tr height="12px"><td></td></tr>';
            xml += '  <tr><td style="font-size: 11pt;"><b>HR Department</b></td></tr>';
            xml += '  <tr height="5px"><td></td></tr>';
            xml += '  <tr><td style="font-size: 9pt; font-style: italic; color: #333333;">Cc: File/Department/Hr/Gom</td></tr>';
            xml += '</table>';

            xml += '</body>';
            xml += '</pdf>';

            // 5. RENDER AND OUTPUT PDF
            const renderer = render.create();
            renderer.templateContent = xml;
            const pdfFile = renderer.renderAsPdf();

            context.response.writeFile({
                file: pdfFile,
                isInline: true
            });

        } catch (e) {
            log.error('NOC Generation Error', e.message);
            context.response.write('System Error: ' + e.message);
        }
    };

    /**
     * Helper: Format Date to "18th June 2026"
     */
    function formatNocDate(dateObj) {
        if (!dateObj) return '';
        const day = dateObj.getDate();
        const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        const month = monthNames[dateObj.getMonth()];
        const year = dateObj.getFullYear();

        let suffix = 'th';
        if (day === 1 || day === 21 || day === 31) suffix = 'st';
        else if (day === 2 || day === 22) suffix = 'nd';
        else if (day === 3 || day === 23) suffix = 'rd';

        return day + suffix + ' ' + month + ' ' + year;
    }

    /**
     * Helper: Escape XML (Used only for plain text, NOT for Rich Text remarks)
     */
    function escapeXml(str) {
        if (!str) return '';
        return str.toString().replace(/&/g, '&amp;')
                           .replace(/</g, '&lt;')
                           .replace(/>/g, '&gt;')
                           .replace(/"/g, '&quot;')
                           .replace(/'/g, '&apos;');
    }

    return { onRequest: onRequest };
});